### ISSUE TITLE
Support for Books as well

### ISSUE THREAD

**Issue by AYA-123** [mProjectsCode/obsidian-media-db-plugin#102]
To expand on your media types, you could add support for books as well, maybe pulling metadata from goodreads, such as Author, ISBN, cover etc.

**Comment by ltctceplrm** [comment]
I'd also love for MediaDB to do books, the the currently existing plugins to add books in Obsidian are lacking compared to MediaDB's capabilities:

- Book Search is pretty okay except that it uses google books as API and it has problems with missing metadata and low resolution covers
- Booksidian uses goodreads which is a great source but it mostly exists to sync with goodreads and so everytime erases any changes or additions made to the note in Obsidian

The problem is that goodreads no longer offers api keys and will stop their usability so first you'd need to find a better free api.

[Openlibrary ](https://openlibrary.org/developers/api) might be a good choice

**Comment by AYA-123** [comment]
I also think OpenLibrary is a good choice - are there currently any restrictions in terms of implementing it?

**Comment by ltctceplrm** [comment]
Well the creator of this plugin @mProjectsCode has said in the past that they didn't want to make the Book Search plugin obsolete and I think they are busy at the moment.

I was tempted to try adding support for books as a PR but I'm not at all proficient with any of this. I still gave it a go and  after several hours of hitting my head against the wall I pretty much succeeded:

I can search by title or by OpenLibrary work ID and the plugin returns metadata for the title, original publish year, author cover, average online rating and median amount of pages across all editions.

Now I just need to figure out how to do a pull request correctly

**Comment by a13ph** [comment]
I guess this can be closed, as books are now supported

**Comment by AYA-123** [comment]
Nice - thanks!
