### ISSUE TITLE
Book Plugin needs a few features

### ISSUE THREAD

**Issue by blu3knight** [mProjectsCode/obsidian-media-db-plugin#115]
**Is your feature request related to a problem? Please describe.**
Currently the book plugin needs a few features added. As it is missing a few things.

**Describe the solution you'd like**
1. ISBN needs to be added back. I saw the commit in terms of releases but ISBN is used for a lot of other areas, Amazon, google books, and Goodreads, etc. in my template I can automatically use it for creating search for these, it is especially useful for books I want to get, or just for links to Amazon.

‘this can be disabled via config as well

2. in search output, author needs to be included so that you can easily find book you want.

**Comment by ltctceplrm** [comment]
The thing with isbn is that it's for a specific edition of a book, so there could be dozens of ISBNs or sometimes even none. Whereas I tried to use the OpenLibrary api to use the actual work ID instead. While the ISBN is not necessarily useful I don't really mind adding it back since indeed it can be disabled in the settings but should the plugin add all the ISBNs? Just the first one?

As for the search: the api allows a general search but then you get the problem that some books would show up very low in the results unless you add the author name, example with Children of Memory by Adrian Tchaikovsky

- https://openlibrary.org/search.json?q=children%20of%20memory
- https://openlibrary.org/search.json?title=children%20of%20memory
- https://openlibrary.org/search.json?q=children%20of%20memory%20adrian%20tchaikovsky

I understand that for some books it'll be the opposite problem if there are 50 books with the same identical title and your author is at the end but I think the current option is the best solution for now. Unless it's possible to change the OpenLibraryAPI.ts file that searching for `children of memory&author=Adrian Tchaikovsky` would change the url to https://openlibrary.org/search.json?title=children%20of%20memory&author=adrian%20tchaikovsky. I don't know if that would be a good solution though because it's kind of half baked and people would have to read the manual to know you can even do this. I'd also have to find a way to work around the URI encoding because currently this search won't parse.

**Comment by ltctceplrm** [comment]
Sure, I'll add it back in and have it select the first isbn from the list then

**Comment by blu3knight** [comment]
I would recommend if option to have isbn (9) and isbn13 as the book plugin does, and any from the list works for that. I am not sure what's available via api.

As for the author search the or title searches the biggest problem is to translate the spaces to be able to be used in url search `%20` so that is the issue that is hard to get around without introducing complexity into pages.

**Comment by ltctceplrm** [comment]
I added a length check and it returns the first isbn of 10 characters or below as `isbn `and the first isbn of 13 characters as `isbn13`.

**Comment by mProjectsCode** [comment]
completed by #116
